# Configuração Básica
spring.application.name=DigiStart
server.port=8081

# Configuração dos Shards (Banco de Dados)
spring.datasource.shard1.jdbc-url=jdbc:postgresql://localhost:5432/digistart_shard1
spring.datasource.shard1.username=postgres
spring.datasource.shard1.password=123
spring.datasource.shard1.driver-class-name=org.postgresql.Driver

spring.datasource.shard2.jdbc-url=jdbc:postgresql://localhost:5432/digistart_shard2
spring.datasource.shard2.username=postgres
spring.datasource.shard2.password=123
spring.datasource.shard2.driver-class-name=org.postgresql.Driver

# Configuração JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway (Migrações)
spring.flyway.enabled=true

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# JWT
jwt.secret=mySecretKeyForDigiStartApplication123456789
jwt.expiration=86400000

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
