CREATE TABLE tb_user (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 2 MINVALUE 2 MAXVALUE 9223372036854775806 START 2 CACHE 1 NO CYCLE) NOT NULL,
	ativo bool DEFAULT true NOT NULL,
	email varchar(255) NOT NULL,
	senha varchar(100) NOT NULL,
	nome varchar(150) NOT NULL,
	tipo varchar(50) NOT NULL,
	CONSTRAINT tb_user_email_key UNIQUE (email),
	CONSTRAINT tb_user_pkey PRIMARY KEY (id),
	CONSTRAINT tb_user_tipo_check CHECK (((tipo)::text = ANY ((ARRAY['ADMIN'::character varying, 'ALUNO'::character varying, 'PROFESSOR'::character varying])::text[])))
);
