CREATE TABLE alunos (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	data_nascimento date NOT NULL,
	nickname varchar(15) NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT alunos_nickname_key UNIQUE (nickname),
	CONSTRAINT alunos_pkey PRIMARY KEY (id),
	CONSTRAINT alunos_user_id_key UNIQUE (user_id),
	CONSTRAINT alunos_user_id_fkey FOREIGN KEY (user_id) REFERENCES tb_user(id) ON DELETE CASCADE
);
